'use strict';
const cards = [
{id:1,caption:'Mengemas mainan',answer:'rajin'},
{id:2,caption:'Tidak mengemas mainan',answer:'malas'},
{id:3,caption:'Menyapu lantai',answer:'rajin'},
{id:4,caption:'Membiarkan lantai kotor',answer:'malas'},
{id:5,caption:'Menyiapkan kerja sekolah',answer:'rajin'},
{id:6,caption:'Mengabaikan kerja sekolah',answer:'malas'},
{id:7,caption:'Mengemas katil',answer:'rajin'},
{id:8,caption:'Membiarkan katil bersepah',answer:'malas'},
{id:9,caption:'Menyusun buku',answer:'rajin'},
{id:10,caption:'Membiarkan buku berselerak',answer:'malas'}
];
const $=id=>document.getElementById(id);
let order=[],position=0,selected=false,locked=false,sound=true,context=null,drag=null,ignoreClick=false,voices=[];
const instruction='Lihat gambar. Seret gambar ke Rumah Rajin atau Rumah Malas.';
function loadVoices(){if('speechSynthesis' in window)voices=speechSynthesis.getVoices();}
if('speechSynthesis' in window){loadVoices();speechSynthesis.addEventListener('voiceschanged',loadVoices);}
function speak(text){if(!sound)return;if(!('speechSynthesis'in window)){ $('audio-note').textContent='Bacaan suara tidak disokong pada pelayar ini. Guru boleh membacakan teks.';return;}loadVoices();speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='ms-MY';utterance.rate=.82;const voice=voices.find(v=>/^ms[-_]/i.test(v.lang)||v.lang==='ms');if(voice)utterance.voice=voice;else $('audio-note').textContent='Jika bacaan kurang jelas, aktifkan suara Bahasa Melayu pada peranti.';utterance.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))$('audio-note').textContent='Suara tidak tersedia. Guru boleh membacakan teks.';};speechSynthesis.speak(utterance);}
function audioReady(){try{context??=new(window.AudioContext||window.webkitAudioContext)();if(context.state==='suspended')context.resume();}catch{}}
function chime(){if(!sound||!context)return;[523.25,659.25,783.99].forEach((f,i)=>{const osc=context.createOscillator(),gain=context.createGain(),t=context.currentTime+i*.11;osc.frequency.value=f;osc.connect(gain);gain.connect(context.destination);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.06,t+.015);gain.gain.exponentialRampToValueAtTime(.001,t+.23);osc.start(t);osc.stop(t+.25);});}
function show(name){['welcome','game','finish'].forEach(id=>$(id).hidden=id!==name);}
function feedback(text,type=''){ $('feedback').textContent=text;$('feedback').className=type;}
function render(){selected=false;locked=false;const c=order[position];$('card').disabled=false;$('card').className='card';$('card').setAttribute('aria-pressed','false');$('card').setAttribute('aria-label',c.caption+'. Sentuh untuk memilih gambar.');$('picture').src=`assets/card-${c.id}.png`;$('picture').alt=c.caption;$('caption').textContent=c.caption;$('hint').textContent='Seret gambar, atau sentuh gambar kemudian rumah.';}
function start(){audioReady();if('speechSynthesis'in window)speechSynthesis.cancel();order=cards.slice();for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}position=0;['rajin','malas'].forEach(v=>$('collected-'+v).replaceChildren());$('progress').textContent='Selesai: 0/10';$('stars').textContent='⭐ 0/10';$('bar').style.width='0%';feedback('Kamu boleh! Lihat perbuatannya dengan teliti.');show('game');render();speak(instruction);$('card').focus({preventScroll:true});}
function select(){if(locked)return;selected=!selected;$('card').classList.toggle('selected',selected);$('card').setAttribute('aria-pressed',String(selected));$('hint').textContent=selected?'Gambar dipilih. Sekarang sentuh sebuah rumah.':'Seret gambar, atau sentuh gambar kemudian rumah.';}
function answer(house){if(locked||!selected||position>=order.length)return;const c=order[position];if(c.answer!==house){selected=false;$('card').classList.remove('selected');$('card').setAttribute('aria-pressed','false');$('hint').textContent='Sentuh gambar untuk mencuba semula.';feedback('Cuba lagi. Lihat perbuatannya.','error');speak('Cuba lagi. Lihat perbuatannya.');return;}locked=true;$('card').disabled=true;feedback('Betul! Bagus!','success');chime();speak('Betul! Bagus!');const target=document.querySelector(`[data-house="${house}"]`).getBoundingClientRect(),source=$('card').getBoundingClientRect();$('card').style.transform=`translate(${target.x+target.width/2-source.x-source.width/2}px,${target.y+target.height/2-source.y-source.height/2}px) scale(.18)`;$('card').style.opacity='0';const thumb=new Image();thumb.src=$('picture').src;thumb.alt=c.caption;$('collected-'+house).append(thumb);position++;$('progress').textContent=`Selesai: ${position}/10`;$('stars').textContent=`⭐ ${position}/10`;$('bar').style.width=position*10+'%';setTimeout(()=>{$('card').style.transform='';$('card').style.opacity='';if(position===10)finish();else{render();$('card').focus({preventScroll:true});}},1100);}
function finish(){show('finish');$('review').replaceChildren();cards.filter(c=>c.answer==='rajin').forEach(c=>{const item=document.createElement('div');item.className='review-card';const img=new Image();img.src=`assets/card-${c.id}.png`;img.alt=c.caption;const p=document.createElement('p');p.textContent=c.caption;const b=document.createElement('button');b.textContent='🔊';b.setAttribute('aria-label','Dengar: '+c.caption);b.onclick=()=>speak(c.caption);item.append(img,p,b);$('review').append(item);});speak('Tahniah! Kamu berjaya mengelaskan 10 gambar! Mari amalkan kerajinan setiap hari.');$('replay').focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'});}
$('start').onclick=start;$('replay').onclick=start;
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'🔊 Bunyi Hidup':'🔇 Bunyi Mati';$('sound').setAttribute('aria-pressed',String(sound));if(!sound&&'speechSynthesis'in window)speechSynthesis.cancel();if(sound)audioReady();};
document.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>speak(b.dataset.say));$('caption-sound').onclick=()=>speak(order[position]?.caption||'');
$('card').onclick=()=>{if(ignoreClick){ignoreClick=false;return;}select();};
document.querySelectorAll('[data-house]').forEach(h=>h.onclick=()=>{if(!selected&&!locked){feedback('Sentuh gambar dahulu. Kemudian sentuh rumah.');return;}answer(h.dataset.house);});
$('card').addEventListener('pointerdown',e=>{if(locked||e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false,ghost:null};$('card').setPointerCapture(e.pointerId);});
$('card').addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;if(!drag.moved&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>9){drag.moved=true;selected=true;drag.ghost=new Image();drag.ghost.src=$('picture').src;drag.ghost.className='drag-ghost';drag.ghost.alt='';document.body.append(drag.ghost);$('card').style.opacity='.35';}if(drag.moved){drag.ghost.style.left=e.clientX-75+'px';drag.ghost.style.top=e.clientY-75+'px';const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-house]');document.querySelectorAll('[data-house]').forEach(h=>h.classList.toggle('over',h===hit));}});
function endDrag(e,cancel=false){if(!drag||drag.id!==e.pointerId)return;const moved=drag.moved;drag.ghost?.remove();drag=null;$('card').style.opacity='';document.querySelectorAll('[data-house]').forEach(h=>h.classList.remove('over'));if(moved){ignoreClick=true;setTimeout(()=>ignoreClick=false,0);const hit=cancel?null:document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-house]');if(hit)answer(hit.dataset.house);else{selected=false;$('card').classList.remove('selected');$('card').setAttribute('aria-pressed','false');}}}
$('card').addEventListener('pointerup',e=>endDrag(e));$('card').addEventListener('pointercancel',e=>endDrag(e,true));
$('picture').onerror=()=>{feedback('Gambar tidak dapat dimuatkan. Muat semula halaman dan cuba lagi.','error');};
cards.forEach(c=>{const img=new Image();img.src=`assets/card-${c.id}.png`;});
